Kish-mish/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kish_mish.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Kish_mish.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;
        private readonly IValuesService _valuesService;


        public AboutController(IAboutService aboutService,
                                IValuesService valuesService)
        {
            _aboutService = aboutService;
            _valuesService = valuesService;
        }



        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var about = await _aboutService.GetAll();
            var values = await _valuesService.GetAll();


            AboutVM model = new()
            {
                About = about,
                Values = values


            };

            return View(model);
        }
    }
}

Kish-mish/Controllers/HomeController.cs
using System.Diagnostics;
using Domain.Entities;
using Kish_mish.ViewModels.User;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg;
using Service.Services.Interfaces;

namespace Kish_mish.Controllers;

public class HomeController : Controller
{
    private readonly ISliderService _sliderService;
    private readonly ICategoryService _categoryService;
    private readonly IHttpContextAccessor _accessor;
    private readonly IProductService _productService;
   
    private readonly IBasketService _basketService;
    private readonly IAboutService _aboutService;
    private readonly UserManager<AppUser> _userManager;
    public HomeController(UserManager<AppUser> userManager,
                         ISliderService sliderService,
                         ICategoryService categoryService,
                         IProductService productService,
                         IBasketService basketService,
                         IAboutService aboutService,
                         IHttpContextAccessor accessor)
    {
        _userManager = userManager;
        _sliderService = sliderService;
        _categoryService = categoryService;
        _productService = productService;
        _basketService = basketService;
        _aboutService = aboutService;
        _accessor = accessor;

    }

    public async Task<IActionResult> Index()
    {
        var categories = await _categoryService.GetAll();
        var products = await _productService.GetAll();
        var sliders = await _sliderService.GetAll();
        var about = await _aboutService.GetAll();
     
        HomeVM model = new()
        {
            Categories = categories,
            Products = products,
            Sliders = sliders,
            About = about
          
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddProductToBasket(int? id)
    {

        if (!User.Identity.IsAuthenticated)
        {
            return Problem();
        }
 
        var user = await _userManager.FindByNameAsync(User.Identity.Name);
        if (id is null) return BadRequest();
        var dbProduct = await _productService.GetById((int)id);
        if (await _basketService.ExistProduct(dbProduct.Name, user.Id))
        {
            await _basketService.IncreaseExistProductCount(dbProduct.Name, user.Id);
            return Ok();
        }


        Basket basket = new()
        {
            ProductName = dbProduct.Name,
            ProductImage = dbProduct.ProductImages.FirstOrDefault(m => m.IsMain).Image,
            ProductCount = 1,
            ProductPrice = dbProduct.Price,
            UserId = user.Id,
        };
        await _basketService.Create(basket);

        List<Basket> products = await _basketService.GetBasketByUser(user.Id);


        int count = await _basketService.GetBasketProductCount(user.Id);
        return Ok(new { count });
    }

}

Kish-mish/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Entities;
using Kish_mish.Areas.Admin.ViewModels.Product;
using Kish_mish.ViewModels.Products;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Kish_mish.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IBasketService _basketService;
        public ProductController(IProductService productService,
                                 ICategoryService categoryService,
                                 UserManager<AppUser> userManager,
                                 IBasketService basketService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _userManager = userManager;
            _basketService = basketService;
        }
        [HttpGet]
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();

            var existProduct = await _productService.GetById((int)id);

            if (existProduct is null) return NotFound();

            ProductDetailVM product = new()
            {
                Id = existProduct.Id,
                Name = existProduct.Name,
                Description = existProduct.Description,
                Price = existProduct.Price,
                Category = existProduct.Category.Name,
                ProductImages = existProduct.ProductImages.Select(m => new ProductImageVM { Image = m.Image, IsMain = m.IsMain }).ToList(),
            };

            List<Category> categories = await _categoryService.GetAll();
            List<Product> products = await _productService.GetAll();

            AppUser user = new();
            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }



            ProductDetailPageVM model = new()
            {
                Product = product,
                Products = products,
                Categories = categories,
            };

            return View(model);
        }

      

        [HttpPost]
        public async Task<IActionResult> AddProductToBasket(int? id, int count)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return Problem();
            }

            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (id is null) return BadRequest();
            var dbProduct = await _productService.GetById((int)id);
            if (await _basketService.ExistProduct(dbProduct.Name, user.Id))
            {
                await _basketService.IncreaseExistProductCount(dbProduct.Name, user.Id, count);
                return Ok();
            }


            Basket basket = new()
            {
                ProductName = dbProduct.Name,
                ProductImage = dbProduct.ProductImages.FirstOrDefault(m => m.IsMain).Image,
                ProductCount = 1,
                ProductPrice = dbProduct.Price,
                UserId = user.Id,
            };
            await _basketService.Create(basket);

            List<Basket> products = await _basketService.GetBasketByUser(user.Id);


            int productCount = await _basketService.GetBasketProductCount(user.Id);
            return Ok(new { productCount });
        }
    }
}

Kish-mish/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Entities;
using Kish_mish.Areas.Admin.ViewModels.Product;
using Kish_mish.Helpers;
using Kish_mish.ViewModels.User;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Kish_mish.Controllers
{
    public class ShopController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IBasketService _basketService;
        public ShopController(IProductService productService,
                              ICategoryService categoryService,
                              UserManager<AppUser> userManager,
                              IBasketService basketService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _userManager = userManager;
            _basketService = basketService;
        }
        public async Task<IActionResult> Index(string searchText, int? price, int? categoryId, string sortType, int page = 1)
        {
            if (searchText is not null)
            {
                var paginatedSearchedDatas = await _productService.GetAllSearchedPaginatedDatas(page, searchText);
                int searchedProductCount = await _productService.GetSearchedCount(searchText);
                int searchedPageCount = _productService.GetPageCount(searchedProductCount, 9);

                Paginate<Product> searchPagination = new(paginatedSearchedDatas, searchedPageCount, page);

                var searchCategories = await _categoryService.GetAll();
                var products = await _productService.GetAll();

                ProductPageVM searchModel = new()
                {
                    Categories = searchCategories,
                    Products = products,
                    Pagination = searchPagination
                };


                return View(searchModel);
            }
            else if (price is not null)
            {
                var filteredDatas = await _productService.GetAllPriceFilteredPaginatedDatas(page, (int)price);
                var filteredProductCount = await _productService.GetPriceFilteredCount((int)price);
                var filteredPageCount = _productService.GetPageCount(filteredProductCount, 9);

                Paginate<Product> filterPagination = new(filteredDatas, filteredPageCount, page);

                var searchCategories = await _categoryService.GetAll();
                var products = await _productService.GetAll();
                ProductPageVM filterModel = new()
                {
                    Categories = searchCategories,
                    Products = products,
                    Pagination = filterPagination,
                };

                return View(filterModel);
            }
            else if (categoryId is not null)
            {
                var categoryFilteredDatas = await _productService.GetCategoryFilteredPaginatedDatas(page, (int)categoryId);
                var categoryFilteredProductCount = await _productService.GetCategoryFilteredCount((int)categoryId);
                var categoryFilteredPageCount = _productService.GetPageCount(categoryFilteredProductCount, 9);

                Paginate<Product> categoryFilterPagination = new(categoryFilteredDatas, categoryFilteredPageCount, page);

                var searchCategories = await _categoryService.GetAll();
                var products = await _productService.GetAll();
                ProductPageVM categoryFilterModel = new()
                {
                    Categories = searchCategories,
                    Products = products,
                    Pagination = categoryFilterPagination,
                };

                return View(categoryFilterModel);
            }
            else if (sortType is not null)
            {
                var sortedDatas = await _productService.GetSortedPaginatedDatas(page, sortType);
                var sortedCount = await _productService.GetCount();
                var sortedPageCount = _productService.GetPageCount(sortedCount, 9);

                Paginate<Product> sortedPagination = new(sortedDatas, sortedPageCount, page);

                var searchCategories = await _categoryService.GetAll();
                var products = await _productService.GetAll();
                ProductPageVM sortedModel = new()
                {
                    Categories = searchCategories,
                    Products = products,
                    Pagination = sortedPagination,
                };

                return View(sortedModel);
            }
            else
            {
                var paginatedDatas = await _productService.GetAllPaginatedDatas(page);
                int productCount = await _productService.GetCount();
                int pageCount = _productService.GetPageCount(productCount, 9);

                Paginate<Product> pagination = new(paginatedDatas, pageCount, page);

                var categories = await _categoryService.GetAll();
                var products = await _productService.GetAll();

                ProductPageVM model = new()
                {
                    Categories = categories,
                    Products = products,
                    Pagination = pagination
                };


                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddProductToBasket(int? id)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return Problem();
            }

            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (id is null) return BadRequest();
            var dbProduct = await _productService.GetById((int)id);
            if (await _basketService.ExistProduct(dbProduct.Name, user.Id))
            {
                await _basketService.IncreaseExistProductCount(dbProduct.Name, user.Id);
                return Ok();
            }


            Basket basket = new()
            {
                ProductName = dbProduct.Name,
                ProductImage = dbProduct.ProductImages.FirstOrDefault(m => m.IsMain).Image,
                ProductCount = 1,
                ProductPrice = dbProduct.Price,
                UserId = user.Id,
            };
            await _basketService.Create(basket);
            List<Basket> products = await _basketService.GetBasketByUser(user.Id);


            int count = await _basketService.GetBasketProductCount(user.Id);
            return Ok(new { count });
        }
    }
}

Kish-mish/Views/Home/Index.cshtml
@model HomeVM


@{
    ViewData["Title"] = "Home Page";
}

@section css {
    <link rel="stylesheet" href="~/assets/css/home.css" />
}


<main>

    <!-- slider starts -->

    <section id="slider-area">
        <div class="container">
            <div class="slider">
                <div class="icons">
                    <i class="fa-solid fa-chevron-left left-icon"></i>
                    <i class="fa-solid fa-chevron-right right-icon"></i>
                </div>
                <div class="images">

                    @foreach (var item in Model.Sliders)
                    {
                        string active = "active-image";

                        if (item != Model.Sliders.FirstOrDefault())
                        {
                            active = "";
                        }


                        <img src="~/assets/images/@item.Image" class="@active">
                    }

                  
                </div>

            </div>

        </div>

    </section>
    <!-- slider ends -->
    <!-- PRODUCTS START -->

    <section id="products">
        <div class="container">
            <div class="row pt-5">
                <div class="col-12 d-flex justify-content-between">
                    <ul class="category-mobile d-md-none list-unstyled">
                        <li>
                            <a href="" class="categories mr-2">Categories</a>
                            <i class="fas fa-caret-down"></i>
                            <ul class="categories list-unstyled" style="display: none;">
                                @foreach (var item in Model.Categories)
                                {
                                    <li><a data-id="@item.Id">@item.Name</a></li>

                                }
   
                            </ul>
                        </li>
                    </ul>
                    <ul class="category d-none d-md-flex list-unstyled">

                        @foreach (var item in Model.Categories.Take(7))
                        {
                            <li class="category-tab" category-id="@item.Id" style="cursor: pointer;"><a >@item.Name</a></li>


                        }
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade show p-0 active">
                    <div class="row">
                        @foreach (var item in Model.Products.Take(8))

                        {
                            <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                                <div class="product-item text-center" category-id="@item.CategoryId">
                                    <div class="img">
                                        <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                            <img src="~/assets/images/@item.ProductImages.FirstOrDefault(m=>m.IsMain).Image" class="img-fluid" alt="">
                                        </a>

                                    </div>
                                    <div class="title mt-3">
                                        <h6>@item.Name</h6>
                                    </div>
                                    <div class="price">
                                        <a data-id="@item.Id" class="add-product-basket"><span class="text-black-50">Səbətə əlavə et</span></a>
                                        <span class="text-black-50">@item.Price₼</span>
                                    </div>
                                </div>
                            </div>
                        }


                        <div class="show-btn mt-5">
                            <button><a asp-controller="Shop" asp-action="Index" style="text-decoration: none; color:white;">Daha çox</a></button>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <!-- PRODUCTS END -->
    <!-- About START -->
    @foreach (var item in Model.About)
    {
        <section id="about">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="content">
                            <h2>Kish-Mish hekayəmiz</h2>
                            <div class="content-text">
                                <p>
                                    @item.Description

                                </p>
                                <a class="about-btn" asp-controller="About" asp-action="Index">Hekayəmizi oxu</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }
    <!-- Customer Review START -->
    <section id="customer-review">
        <div class="container">
            <div class="indicator">
                <span class="btn active"></span>
                <span class="btn"></span>
                <span class="btn"></span>
                <span class="btn"></span>
            </div>
            <div class="testimonial">
                <div class="row testimonials" id="slide-row">
                    <div class="col-12 item">
                        <div class="content-testimonial">
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis tenetur ipsa ut.
                                Esse asperiores quisquam quos blanditiis quaerat voluptatum. Voluptatum assumenda
                                impedit culpa ipsam. Ea, sequi. Perferendis laborum nisi iure.
                            </p>
                            <h2>Nisa</h2>
                            <p>Customer</p>
                        </div>
                        <div class="image">
                            <img src="~/assets/images/instagram7.jpeg">
                        </div>
                    </div>
                    <div class="col-12 item">
                        <div class="content-testimonial">
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis tenetur ipsa ut.
                                Esse asperiores quisquam quos blanditiis quaerat voluptatum. Voluptatum assumenda
                                impedit culpa ipsam. Ea, sequi. Perferendis laborum nisi iure.
                            </p>
                            <h2>Rufana</h2>
                            <p>Customer</p>
                        </div>
                        <div class="image">
                            <img src="~/assets/images/instagram8.jpeg">
                        </div>
                    </div>
                    <div class="col-12 item">
                        <div class="content-testimonial">
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis tenetur ipsa ut.
                                Esse asperiores quisquam quos blanditiis quaerat voluptatum. Voluptatum assumenda
                                impedit culpa ipsam. Ea, sequi. Perferendis laborum nisi iure.
                            </p>
                            <h2>Alihuseyn</h2>
                            <p>Customer</p>
                        </div>
                        <div class="image">
                            <img src="~/assets/images/instagram10.jpeg">
                        </div>
                    </div>
                    <div class="col-12 item">
                        <div class="content-testimonial">
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis tenetur ipsa ut.
                                Esse asperiores quisquam quos blanditiis quaerat voluptatum. Voluptatum assumenda
                                impedit culpa ipsam. Ea, sequi. Perferendis laborum nisi iure.
                            </p>
                            <h2>Yegana</h2>
                            <p>Customer</p>
                        </div>
                        <div class="image">
                            <img src="~/assets/images/instagram12.jpeg">
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </section>



    <!-- About END -->
    <!-- Instagram START -->
    <section id="instagram">
        <div class="owl-carousel instagram">
            <div class="item"><img src="~/assets/images/instagram2.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram3.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram12.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram4.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram5.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instragram6.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram9.jpeg" class="img-fluid" alt=""></div>
            <div class="item"><img src="~/assets/images/instagram10.jpeg" class="img-fluid" alt=""></div>
        </div>


    </section>
    <!-- Instagram END -->






</main>